#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myland
    username: root
    password: 200105
    driver-class-name: com.mysql.cj.jdbc.Driver
#上传文件单个最大3mb，请求最大10mb
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
# 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false